package mk.kanta.app.core.designsystem

import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.shadow
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Shape
import androidx.compose.ui.unit.dp

/**
 * Spec §3.3: "Elevation: almost none. Separate things with background tone and 1dp hairlines.
 * Only the bottom sheet and the primary floating button get a soft shadow (y 8, blur 24, 8% black)."
 *
 * Deliberately the ONLY shadow in the app. Everything else separates with [Spacing.hairline]
 * and surface tone. If you are reaching for this on a third surface, the design is drifting.
 *
 * Implementation note: Android's shadows are generated by the platform from an elevation value
 * and a light position — blur radius and y-offset are not separately settable. 12dp elevation is
 * the closest match to the spec's "y 8, blur 24"; the 8% black is applied exactly via the ambient
 * and spot colours (honoured on API 28+; below that the platform draws its own black shadow).
 */
private val SoftShadowElevation = 12.dp
private val SoftShadowColor = Color.Black.copy(alpha = 0.08f)

fun Modifier.kantaSoftShadow(
    shape: Shape,
    clip: Boolean = false,
): Modifier = this.shadow(
    elevation = SoftShadowElevation,
    shape = shape,
    clip = clip,
    ambientColor = SoftShadowColor,
    spotColor = SoftShadowColor,
)
